batch_size: 1
bcs: null
config: false
data_root: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized
gpus: 0
input_size: 200
length_x: 6.0
length_y: 3.0
load_name: F
lr: 0.0001
max_epochs: 3000
max_iters: 10000
mean_heat: 0
mean_layout: 0.0
model_name: fpn
num_workers: 4
nx: 256
ny: 128
profiler: false
resume_from_checkpoint: null
seed: 34
std_heat: 1
std_layout: 1.0
test_args: false
test_dir: train
test_list: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized/test.txt
train_dir: train
train_list: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized/train.txt
u_D: 298.0
use_16bit: false
val_check_interval: 1.0
val_dir: train
val_list: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized/val.txt
