# config

# dataset path
#data_root: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/complex_component/FDM
data_root: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized
train_dir: train
val_dir: train
test_dir: train
train_list: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized/train.txt
val_list: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized/val.txt
test_list: /home/hero/Data/heat_layout_data/200x200_0.045_0.055/nse_ref_geom_resized/test.txt

# dataset properties
load_name: F # F, list
length_x: 6
length_y: 3
nx: 256 # select from [50, 100, 150, 200, 400, 800]
ny: 128
u_D: 298
seed: 34
bcs:
#  - [[0, 0.15],[0, 0.25]]
#  - [[0.0400, 0.0], [0.0600, 0.0]]
#  - [[0.0495, 0.0], [0.0505, 0.0]]
#  - [[0.0450, 0.0], [0.0550, 0.0]]
#  - [[]]

batch_size: 1
max_epochs: 3000
lr: 0.0001
# the id of chosen gpu
gpus: 0
val_check_interval: 1.0
# num_workers in dataloader
num_workers: 4

# preprocessing of data
# input
mean_layout: 0
std_layout: 1
# output
# mean_heat: 0
# std_heat: 1

# physical properties
#nu: 0.05

# boundary condition
# NSE
#inlet: [3,0] # [u,v] m/s
#outlet: 0 # p
#nonslip: [0,0] # [u,v]
